substitutions:
  friendly_name: Zehnder Q350
  device_name: zehnder-comfoair-q
  device_description: Zehnder Q350
  filter_time: 5s
  filter_send_every: "1"
  filter_window_size: "3"

packages:
  binary_sensors: !include binary_sensors.yml
  board: !include board.yml
  button: !include button.yml
  canbus: !include canbus.yml
  common: !include common.yml
  fan: !include fan.yml
  select: !include select.yml
  sensors: !include sensors.yml
  switch: !include switch.yml
  text_sensors: !include text_sensors.yml

esphome:
  name: ${device_name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
#  comment: ${device_description}
  project:
    name: yoziru.esphome-zehnder-comfoair
    version: "2024.8.0"
  on_boot:
    priority: -200
    then:
      - lambda: |-
          id(last_reboot_reason) = esp_reset_reason();
          ESP_LOGE("boot", "Reboot reason saved: %d", id(last_reboot_reason));

logger:
  level: VERY_VERBOSE
    
ota:
  - platform: web_server

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s
  enable_rrm: true
  enable_btm: true
  fast_connect: true

web_server:
  port: 80
  version: 3
  sorting_groups:
    - id: sorting_group_control
      name: "Control"
      sorting_weight: 1
    - id: sorting_group_boost
      name: "Boost"
      sorting_weight: 2
    - id: sorting_group_bypass
      name: "Bypass"
      sorting_weight: 3
    - id: sorting_group_humidity
      name: "Humidity"
      sorting_weight: 4
    - id: sorting_group_temperature
      name: "Temperature"
      sorting_weight: 5
    - id: sorting_group_energy
      name: "Energy"
      sorting_weight: 6
    - id: sorting_group_sensors
      name: "Sensors"
      sorting_weight: 7
    - id: sorting_group_wifi_module
      name: "WiFi Module"
      sorting_weight: 8
    
  auth:
    username: !secret user
    password: !secret pass

globals:
  - id: last_reboot_reason
    type: int
    restore_value: yes
    initial_value: '-1'

# See docs: https://github.com/michaelarnauts/aiocomfoconnect/blob/master/docs/PROTOCOL-PDO.md
zehnder_comfoair_q:
  id: comfoair
  request_ids:
    [
      16,
      49,
      54,
      55,
      65,
      66,
      67,
      81,
      82,
      117,
      118,
      119,
      120,
      121,
      122,
      128,
      129,
      130,
      192,
      209,
      210,
      211,
      212,
      212,
      213,
      214,
      215,
      216,
      217,
      218,
      220,
      221,
      225,
      227,
      274,
      275,
      276,
      277,
      278,
      290,
      291,
      292,
      293,
      294,
    ]
