.throttle-filter: &throttle-filter
  - throttle_average: "${filter_time}"
  - filter_out: nan
  - sliding_window_moving_average:
      {send_every: "${filter_send_every}", window_size: "${filter_window_size}"}

.throttle-filter-round-tens: &throttle-filter-round-tens
  - throttle_average: "${filter_time}"
  - filter_out: nan
  - sliding_window_moving_average:
      {send_every: "${filter_send_every}", window_size: "${filter_window_size}"}
  - lambda: return round(x/10)*10;

.throttle-filter-e-3: &throttle-filter-e-3
  - throttle_average: "${filter_time}"
  - filter_out: nan
  - sliding_window_moving_average:
      {send_every: "${filter_send_every}", window_size: "${filter_window_size}"}
  - multiply: 0.001

sensor:
  - platform: template
    id: away_indicator_raw # PDO 16
    name: "away_indicator_raw"
    internal: true
    accuracy_decimals: 0
    on_value:
      then:
        - lambda: id(away_indicator).publish_state(x == 7);

  - platform: template
    id: fan_level_raw # PDO 65
    name: "fan_level_raw"
    internal: true
    accuracy_decimals: 0
    on_value:
      then:
        - lambda: id(fan_level).publish_state(std::to_string(int(x)));
        - if:
            condition:
              lambda: "return int(x) == 0;"
            then:
              - fan.turn_off: comfoair_fan
            else:
              - fan.turn_on:
                  id: comfoair_fan
                  speed: !lambda "return int(x);"

  - platform: template
    id: next_fan_change_in_raw # PDO 81
    name: "next_fan_change_in_raw"
    accuracy_decimals: 0
    device_class: duration
    unit_of_measurement: "s"
    internal: true
    filters:
      - throttle: 0.5s
    on_value:
      then:
        - lambda: id(next_fan_change_in).publish_state(id(comfoair)->seconds_to_human_readable(x));

  - platform: template
    id: next_bypass_change_in_raw # PDO 82
    name: "next_bypass_change_in_raw"
    accuracy_decimals: 0
    device_class: duration
    unit_of_measurement: "s"
    internal: true
    filters:
      - throttle: 0.5s
    on_value:
      then:
        - lambda: id(next_bypass_change_in).publish_state(id(comfoair)->seconds_to_human_readable(x));

  - platform: template
    id: exhaust_fan_duty # PDO 117
    name: "Exhaust Fan Duty"
    web_server:
      sorting_group_id: sorting_group_sensors
      sorting_weight: 16
    accuracy_decimals: 0
    unit_of_measurement: "%"
    state_class: measurement
    filters: *throttle-filter

  - platform: template
    id: supply_fan_duty # PDO 118
    name: "Supply Fan Duty"
    web_server:
      sorting_group_id: sorting_group_sensors
      sorting_weight: 15
    accuracy_decimals: 0
    unit_of_measurement: "%"
    state_class: measurement
    filters: *throttle-filter

  - platform: template
    id: supply_fan_flow # PDO 119
    name: "Supply Fan Flow"
    icon: mdi:gauge
    web_server:
      sorting_group_id: sorting_group_control
      sorting_weight: 5
    accuracy_decimals: 0
    unit_of_measurement: "m³/h"
    state_class: measurement
    filters: *throttle-filter

  - platform: template
    id: exhaust_fan_flow # PDO 120
    name: "Exhaust Fan Flow"
    icon: mdi:gauge
    web_server:
      sorting_group_id: sorting_group_control
      sorting_weight: 6
    accuracy_decimals: 0
    unit_of_measurement: "m³/h"
    state_class: measurement
    filters: *throttle-filter

  - platform: template
    id: exhaust_fan_speed # PDO 121
    name: "Exhaust Fan Speed"
    icon: mdi:speedometer
    web_server:
      sorting_group_id: sorting_group_sensors
      sorting_weight: 14
    accuracy_decimals: 0
    unit_of_measurement: "rpm"
    state_class: measurement
    filters: *throttle-filter-round-tens

  - platform: template
    id: supply_fan_speed # PDO 122
    name: "Supply Fan Speed"
    icon: mdi:speedometer
    web_server:
      sorting_group_id: sorting_group_sensors
      sorting_weight: 13
    accuracy_decimals: 0
    unit_of_measurement: "rpm"
    state_class: measurement
    filters: *throttle-filter-round-tens

  - platform: template
    id: power # PDO 128
    name: "Power"
    web_server:
      sorting_group_id: sorting_group_energy
      sorting_weight: 1
    accuracy_decimals: 0
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    filters: *throttle-filter

  - platform: template
    id: energy_ytd # PDO 129
    name: "Energy YTD"
    web_server:
      sorting_group_id: sorting_group_energy
      sorting_weight: 2
    accuracy_decimals: 0
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing

  - platform: template
    id: energy_since_start # PDO 130
    name: "Energy Total"
    web_server:
      sorting_group_id: sorting_group_energy
      sorting_weight: 3
    accuracy_decimals: 0
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing

  - platform: template
    id: filter_replacement_remaining_days # PDO 192
    name: "Filter Replacement"
    icon: mdi:air-filter
    web_server:
      sorting_group_id: sorting_group_sensors
      sorting_weight: 9
    accuracy_decimals: 0
    unit_of_measurement: "days"

  - platform: template
    id: running_mean_outdoor_temp # PDO 209
    name: "Running Mean Outdoor Temperature"
    internal: true
    filters: [multiply: 0.1]
    accuracy_decimals: 1
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement

  - platform: template
    id: heating_season_raw # PDO 210
    accuracy_decimals: 0
    on_value:
      then:
        - lambda: id(heating_season).publish_state(x == 1);

  - platform: template
    id: cooling_season_raw # PDO 211
    accuracy_decimals: 0
    on_value:
      then:
        - lambda: id(cooling_season).publish_state(x == 1);

  - platform: template
    id: profile_target_temp # PDO 212
    name: "Profile Target"
    web_server:
      sorting_group_id: sorting_group_temperature
      sorting_weight: 7
    filters: [multiply: 0.1]
    accuracy_decimals: 1
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement

  - platform: template
    id: avoided_heating_actual # PDO 213
    name: "Saved Heating"
    web_server:
      sorting_group_id: sorting_group_energy
      sorting_weight: 4
    filters: *throttle-filter-e-3
    accuracy_decimals: 3
    unit_of_measurement: "kW"
    device_class: power
    state_class: measurement

  - platform: template
    id: avoided_heating_ytd # PDO 214
    name: "Saved Heating YTD"
    web_server:
      sorting_group_id: sorting_group_energy
      sorting_weight: 5
    accuracy_decimals: 0
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing

  - platform: template
    id: avoided_heating_total # PDO 215
    name: "Saved Heating Total"
    web_server:
      sorting_group_id: sorting_group_energy
      sorting_weight: 6
    accuracy_decimals: 0
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing

  - platform: template
    id: avoided_cooling_actual # PDO 216
    name: "Saved Cooling"
    web_server:
      sorting_group_id: sorting_group_energy
      sorting_weight: 7
    filters: *throttle-filter-e-3
    accuracy_decimals: 3
    unit_of_measurement: "kW"
    device_class: power
    state_class: measurement

  - platform: template
    id: avoided_cooling_ytd # PDO 217
    name: "Saved Cooling YTD"
    web_server:
      sorting_group_id: sorting_group_energy
      sorting_weight: 8
    accuracy_decimals: 0
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing

  - platform: template
    id: avoided_cooling_total # PDO 218
    name: "Saved Cooling Total"
    web_server:
      sorting_group_id: sorting_group_energy
      sorting_weight: 9
    accuracy_decimals: 0
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing

  - platform: template
    id: pre_heater_temp_before # PDO 220
    name: "Pre-heater Temperature Before"
    internal: true
    filters: [multiply: 0.1]
    accuracy_decimals: 1
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement

  - platform: template
    id: post_heater_temp_after # PDO 221
    name: "Post-heater Temperature After"
    internal: true
    filters: [multiply: 0.1]
    accuracy_decimals: 1
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement

  - platform: template
    id: bypass_state # PDO 227
    name: "Bypass State"
    web_server:
      sorting_group_id: sorting_group_bypass
      sorting_weight: 1
    accuracy_decimals: 0
    unit_of_measurement: "%"
    state_class: measurement

  - platform: template
    id: extract_air_temp # PDO 274
    name: "Extract Air Temp"
    web_server:
      sorting_group_id: sorting_group_temperature
      sorting_weight: 1
    filters: [multiply: 0.1]
    accuracy_decimals: 1
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement

  - platform: template
    id: exhaust_air_temp # PDO 275
    name: "Exhaust Air Temp"
    web_server:
      sorting_group_id: sorting_group_temperature
      sorting_weight: 4
    filters: [multiply: 0.1]
    accuracy_decimals: 1
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement

  - platform: template
    id: outdoor_air_temp # PDO 276
    name: "Outdoor Air Temp"
    web_server:
      sorting_group_id: sorting_group_temperature
      sorting_weight: 3
    filters: [multiply: 0.1]
    accuracy_decimals: 1
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement

  - platform: template
    id: pre_heater_temp_after # PDO 277, after ComfoFond/GHE
    name: "Pre-heater Temp After"
    internal: true
    filters: [multiply: 0.1]
    accuracy_decimals: 1
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement

  - platform: template
    id: supply_air_temp # PDO 278
    name: "Supply Air Temp"
    web_server:
      sorting_group_id: sorting_group_temperature
      sorting_weight: 2
    filters: [multiply: 0.1]
    accuracy_decimals: 1
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement

  - platform: template
    id: extract_air_humidity # PDO 290
    name: "Extract Air Hum"
    web_server:
      sorting_group_id: sorting_group_humidity
      sorting_weight: 1
    accuracy_decimals: 0
    unit_of_measurement: "%"
    device_class: humidity
    state_class: measurement

  - platform: template
    id: exhaust_air_humidity # PDO 291
    name: "Exhaust Air Hum"
    web_server:
      sorting_group_id: sorting_group_humidity
      sorting_weight: 4
    accuracy_decimals: 0
    unit_of_measurement: "%"
    device_class: humidity
    state_class: measurement

  - platform: template
    id: outdoor_air_humidity # PDO 292, is this really still correct with ComfoFond/GHE installed?
    name: "Outdoor Air Hum"
    web_server:
      sorting_group_id: sorting_group_humidity
      sorting_weight: 3
    accuracy_decimals: 0
    unit_of_measurement: "%"
    device_class: humidity
    state_class: measurement

  - platform: template
    id: pre_heater_humidity_after # PDO 293
    name: "Pre-heater Humidity After"
    internal: true
    accuracy_decimals: 0
    unit_of_measurement: "%"
    device_class: humidity
    state_class: measurement

  - platform: template
    id: supply_air_humidity # PDO 294
    name: "Supply Air Hum"
    web_server:
      sorting_group_id: sorting_group_humidity
      sorting_weight: 2
    accuracy_decimals: 0
    unit_of_measurement: "%"
    device_class: humidity
    state_class: measurement
